import "ShObjIdl.idl";

[
	uuid(204306FD-15A9-40AB-A450-3E355EDDDA75),
	version(2.1)
]
library ImageResizerLib
{
	[uuid(4CF20B46-D006-4B90-A64B-DBAA9470EFBE)]
	coclass ContextMenuHandler
	{
		interface IShellExtInit;
		interface IContextMenu;
	};
};
