//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BriceLambson.ImageResizer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShrinkOnly {
            get {
                return ((bool)(this["ShrinkOnly"]));
            }
            set {
                this["ShrinkOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReplaceOriginals {
            get {
                return ((bool)(this["ReplaceOriginals"]));
            }
            set {
                this["ReplaceOriginals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int QualityLevel {
            get {
                return ((int)(this["QualityLevel"]));
            }
            set {
                this["QualityLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfResizeSize xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <ResizeSize>
    <Name>Small</Name>
    <Mode>Scale</Mode>
    <Width>854</Width>
    <Height>480</Height>
    <Unit>Pixels</Unit>
  </ResizeSize>
  <ResizeSize>
    <Name>Medium</Name>
    <Mode>Scale</Mode>
    <Width>1366</Width>
    <Height>768</Height>
    <Unit>Pixels</Unit>
  </ResizeSize>
  <ResizeSize>
    <Name>Large</Name>
    <Mode>Scale</Mode>
    <Width>1920</Width>
    <Height>1080</Height>
    <Unit>Pixels</Unit>
  </ResizeSize>
  <ResizeSize>
    <Name>Mobile</Name>
    <Mode>Scale</Mode>
    <Width>320</Width>
    <Height>480</Height>
    <Unit>Pixels</Unit>
  </ResizeSize>
</ArrayOfResizeSize>")]
        public global::System.Collections.Generic.List<BriceLambson.ImageResizer.Model.ResizeSize> DefaultSizes {
            get {
                return ((global::System.Collections.Generic.List<BriceLambson.ImageResizer.Model.ResizeSize>)(this["DefaultSizes"]));
            }
            set {
                this["DefaultSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedIndex {
            get {
                return ((int)(this["SelectedIndex"]));
            }
            set {
                this["SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<CustomSize xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http" +
            "://www.w3.org/2001/XMLSchema\">\r\n  <Mode>Scale</Mode>\r\n  <Width>1280</Width>\r\n  <" +
            "Height>720</Height>\r\n  <Unit>Pixels</Unit>\r\n</CustomSize>")]
        public global::BriceLambson.ImageResizer.Model.CustomSize CustomSize {
            get {
                return ((global::BriceLambson.ImageResizer.Model.CustomSize)(this["CustomSize"]));
            }
            set {
                this["CustomSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} ({1})")]
        public string FileNameFormat {
            get {
                return ((string)(this["FileNameFormat"]));
            }
            set {
                this["FileNameFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alpha")]
        public global::BriceLambson.ImageResizer.Model.UpdateFilter UpdateFilter {
            get {
                return ((global::BriceLambson.ImageResizer.Model.UpdateFilter)(this["UpdateFilter"]));
            }
            set {
                this["UpdateFilter"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://imageresizer.svn.codeplex.com/svn/releases.xml")]
        public string UpdateUrl {
            get {
                return ((string)(this["UpdateUrl"]));
            }
        }
    }
}
